Set wait_for_capacity_timeout for asg_node_group
For the switch to using eks_addons, we'll need to ensure that nodes are
up and running before trying to provision them.

Otherwise we end up in a race condition and get errors of the kind:
```
Error: unexpected EKS Add-On (terraform-aws-eks-testing-jPfg0J:coredns)
state returned during creation: unexpected state 'DEGRADED', wanted
target 'ACTIVE'. last error: %!!(MISSING)s(<nil>)
```